
export const FETCH_REPO_REQUEST = "FETCH_REPO_REQUEST"
export const FETCH_REPO_SUCCES = "FETCH_REPO_SUCCES"
export const FETCH_REPO_FAILURE = "FETCH_REPO_FAILURE"
export const GET_TOKEN = "GET_TOKEN"

